echo start process!
set -x # -e stop when any code raise error; -x print command
start_time=$(date +%s)

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_abn-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_abn-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_abn-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_nor-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list  --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-no_nor-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/violence-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-seed0

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg2-CLIP_B-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucf-CLIP_B-seed0

#python main.py --seed 0 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list --beta 0.001 --gama 0.1 --exp-name violence-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list --beta 0.001 --gama 0.1
#python main.py --seed 3407 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list --beta 0.001 --gama 0.1

#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-seed3407
#
#python main.py --seed 0 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-3000e-seed0
#python main.py --seed 228 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-3000e-seed228
#python main.py --seed 3407 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_nor-3000e-seed3407

#
#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_abn-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_abn-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-no_abn-seed3407
#
#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucfg1-CLIP_B-seed3407
#
#python main.py --seed 0 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucf-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucf-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --beta 0.001 --gama 0.1 --exp-name ucf-CLIP_B-seed3407

python ./tools/quick_get_best_AP.py
python ./tools/quick_get_best_AUC.py

end_time=$(date +%s)
runtime_hours=$(((end_time - start_time)/3600))
echo "任务运行时间：$runtime_hours 小时"
date +"%Y-%m-%d %H:%M:%S"