echo start process!
set -x # -e stop when any code raise error; -x print command
start_time=$(date +%s)

#4.18
CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy linear_cosine --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_lin_cos-seed3407 &
CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy exponential_step --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_exp_stp-seed3407 &
CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy cosine_none --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_cos_non-seed3407
wait
echo "4.18 ucfg2-CLIP_L-VLR0.5-VLR_S_lin-seed3407 Run finish!"

CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy linear_cosine --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_lin_cos-seed0 &
CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy exponential_step --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_exp_stp-seed0 &
CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy cosine_none --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_cos_non-seed0
wait
echo "4.18 ucfg2-CLIP_L-VLR0.5-VLR_S_lin-seed0 Run finish!"

CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy linear_cosine --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_lin_cos-seed228 &
CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy exponential_step --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_exp_stp-seed228 &
CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --VLR_Strategy cosine_none --exp-name ucfg2-CLIP_L-VLR0.5-VLR_S_cos_non-seed228
wait
echo "4.18 ucfg2-CLIP_L-VLR0.5-VLR_S_lin-seed228 Run finish!"

##4.4
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.25-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 0 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.5-seed0 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 0 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.75-seed0
#wait
#echo "4.4 ucfg2-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed0 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.25-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 0 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.5-seed0 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 0 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.75-seed0
#wait
#echo "4.4 ucfg1-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed0 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 228 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.25-seed228 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 228 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.75-seed228
#wait
#echo "4.4 ucfg2-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed228 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 228 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.25-seed228 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 228 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.75-seed228
#wait
#echo "4.4 ucfg1-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed228 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.5-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSRv2_0.75-seed3407
#wait
#echo "3.30 ucfg2-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed3407 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.5-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSRv2_0.75-seed3407
#wait
#echo "3.30 ucfg1-CLIP_L-VLR0.5-DSRv2_0.25/0.5/0.75-seed3407 Run finish!"


#4.2
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.25-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 0 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.5-seed0 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 0 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.75-seed0
#wait
#echo "4.2 ucfg2-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed0 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.25-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 0 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.5-seed0 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 0 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.75-seed0
#wait
#echo "4.2 ucfg1-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed0 Run finish!"

#4.1
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 228 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.25-seed228 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 228 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.75-seed228
#wait
#echo "3.30 ucfg2-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed228 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 228 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.25-seed228 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 228 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.75-seed228
#wait
#echo "3.30 ucfg1-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed228 Run finish!"


#4.1
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --DSR 0.25 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --DSR 0.50 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.5-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --DSR 0.75 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-DSR0.75-seed3407
#wait
#echo "3.30 ucfg2-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed3407 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --DSR 0.25 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --DSR 0.50 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.5-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --DSR 0.75 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_L-VLR0.5-DSR0.75-seed3407
#wait
#echo "3.30 ucfg1-CLIP_L-VLR0.5-DSR0.25/0.5/0.75-seed3407 Run finish!"

#3.30
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --VLR 0.1 --exp-name ucfg2-CLIP_L-VLR0.1-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --VLR 0.25 --exp-name ucfg2-CLIP_L-VLR0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_L-VLR0.5-seed3407
#wait
#echo "3.30 ucfg2-CLIP_L-VLR0.1/0.25/0.5 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --VLR 1.0 --exp-name ucfg2-CLIP_L-VLR1-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --VLR 2.0 --exp-name ucfg2-CLIP_L-VLR2-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32  --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 4.0 --exp-name ucfg2-CLIP_L-VLR4-seed3407
#wait
#echo "3.30 ucfg2-CLIP_L-VLR1.0/2.0/4.0 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 3407 --data_sampling_rate 0.25 --feat_extractor clip --dataset ucfcrime --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucf-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_L-SDR0.25-seed3407 &
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3407 --data_sampling_rate 0.5 --feat_extractor clip --dataset ucfcrime --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucf-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_L-SDR0.5-seed3407 &
#CUDA_VISIBLE_DEVICES=2 python main.py --seed 3407 --data_sampling_rate 0.75 --feat_extractor clip --dataset ucfcrime --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucf-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_L-SDR0.75-seed3407
#wait
#echo "3.30 ucf-CLIP_L-DSR Run finish!"

## CLIP-L
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 3407 --feat_extractor clip --dataset ucfcrime --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucf-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_L-seed3407 &
##CLIP-L g1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucfg1-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_L-seed3407 &
##CLIP-L g2
#CUDA_VISIBLE_DEVICES=2 python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 768 --batch-size 32 --rgb_list list/GV-CLIP-L/ucfg2-clip.list --test_rgb_list list/GV-CLIP-L/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_L-seed3407
#wait
#echo "3.27 ucf-CLIP_L-raw/g1/g2 Run finish!"

#CUDA_VISIBLE_DEVICES=0 python main.py --seed 0 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/clip_nomean/ucf-clip.list --test_rgb_list list/clip_nomean/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-nomean-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 228 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/clip_nomean/ucf-clip.list --test_rgb_list list/clip_nomean/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-nomean-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main.py --seed 3407 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/clip_nomean/ucf-clip.list --test_rgb_list list/clip_nomean/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-nomean-seed3407
#wait
#echo "3.27 ucf-CLIP_B-nomean Run finish!"

#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 1.5 --exp-name ucfg2-CLIP_B-VLR1.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 1.5 --exp-name ucfg2-CLIP_B-VLR1.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 1.5 --exp-name ucfg2-CLIP_B-VLR1.5-seed3407
#wait
#echo "3.26 ucfg2-CLIP_B-VLR1.5 Run finish!"

## 3.19
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.5 --exp-name ucfg2-CLIP_B-VLR2.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.5 --exp-name ucfg2-CLIP_B-VLR2.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.5 --exp-name ucfg2-CLIP_B-VLR2.5-seed3407
#wait
#echo "3.19 ucfg2-CLIP_B-VLR2.5 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 3 --exp-name ucfg2-CLIP_B-VLR3-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 3 --exp-name ucfg2-CLIP_B-VLR3-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 3 --exp-name ucfg2-CLIP_B-VLR3-seed3407
#wait
#echo "3.19 ucfg2-CLIP_B-VLR3 Run finish!"
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 5 --exp-name ucfg2-CLIP_B-VLR5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 5 --exp-name ucfg2-CLIP_B-VLR5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 5 --exp-name ucfg2-CLIP_B-VLR5-seed3407
#wait
#echo "3.19 ucfg2-CLIP_B-VLR5 Run finish!"
##---
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV2-alpha0.1-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV2-alpha0.1-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV2-alpha0.1-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV2-alpha0.1 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV2-alpha0.2-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV2-alpha0.2-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV2-alpha0.2-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV2-alpha0.2 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV2-alpha0.4-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV2-alpha0.4-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV2-alpha0.4-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV2-alpha0.4 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV2-alpha0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV2-alpha0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV2-alpha0.5-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV2-alpha0.5 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV1-alpha0.1-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV1-alpha0.1-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.1 --exp-name ucf-CLIP_B-mixV1-alpha0.1-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV1-alpha0.1 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV1-alpha0.2-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV1-alpha0.2-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.2 --exp-name ucf-CLIP_B-mixV1-alpha0.2-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV1-alpha0.2 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV1-alpha0.4-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV1-alpha0.4-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.4 --exp-name ucf-CLIP_B-mixV1-alpha0.4-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV1-alpha0.4 Run finish on 4x4090! "
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV1-alpha0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV1-alpha0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v1 --mixup_alpha 0.5 --exp-name ucf-CLIP_B-mixV1-alpha0.5-seed3407
#wait
#echo "3.19 ucf-CLIP_B-mixV1-alpha0.5 Run finish on 4x4090! "

# 3.17
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 0 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --exp-name ucf-CLIP_B-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 228 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --exp-name ucf-CLIP_B-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main.py --seed 3407 --feat_extractor clip --dataset ucf --feature-size 512 --batch-size 32 --rgb_list list/GV/ucf-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --exp-name ucf-CLIP_B-seed3407
#wait
#echo "3.17 ucf-CLIP_B Run finish on 4x4090! "
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucfg2-CLIP_B-mixV2-alpha0.1-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucfg2-CLIP_B-mixV2-alpha0.1-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.1 --exp-name ucfg2-CLIP_B-mixV2-alpha0.1-seed3407
#wait
#echo "3.17 ucfg2-CLIP_B-mixV2-alpha0.1 Run finish on 4x4090! "
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucfg2-CLIP_B-mixV2-alpha0.2-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucfg2-CLIP_B-mixV2-alpha0.2-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.2 --exp-name ucfg2-CLIP_B-mixV2-alpha0.2-seed3407
#wait
#echo "3.17 ucfg2-CLIP_B-mixV2-alpha0.2 Run finish on 4x4090! "
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.3 --exp-name ucfg2-CLIP_B-mixV2-alpha0.3-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.3 --exp-name ucfg2-CLIP_B-mixV2-alpha0.3-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.3 --exp-name ucfg2-CLIP_B-mixV2-alpha0.3-seed3407
#wait
#echo "3.17 ucfg2-CLIP_B-mixV2-alpha0.3 Run finish on 4x4090! "

# 3.10
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-mixV2-alpha0.6-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-mixV2-alpha0.6-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-mixV2-alpha0.6-seed3407
#wait
#echo "3.10 ucfg2-CLIP_B-mixV2-alpha0.6 Run finish on 4x4090! "
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-mixV2-alpha0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-mixV2-alpha0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-mixV2-alpha0.5-seed3407
#wait
#echo "3.10 ucfg2-CLIP_B-mixV2-alpha0.5 Run finish on 4x4090!"
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-mixV2-alpha0.6-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-mixV2-alpha0.6-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-mixV2-alpha0.6-seed3407
#wait
#echo "3.10 ucfg1-CLIP_B-mixV2-alpha0.6 Run finish on 4x4090!"
#
#CUDA_VISIBLE_DEVICES=0 python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-mixV2-alpha0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-mixV2-alpha0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt --mixup_version v2 --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-mixV2-alpha0.5-seed3407
#wait
#echo "3.10 ucfg1-CLIP_B-mixV2-alpha0.5 Run finish on 4x4090!"

# 3.9
#python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-alpha0.6-seed0
#python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-alpha0.6-seed228
#python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg2-CLIP_B-alpha0.6-seed3407
#echo "3.9 ucfg2-CLIP_B-alpha0.6 Run finish on 3090! "
#
#python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-alpha0.5-seed0
#python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-alpha0.5-seed228
#python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg2-CLIP_B-alpha0.5-seed3407
#echo "3.9 ucfg2-CLIP_B-alpha0.5 Run finish on 3090!"
#
#python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-alpha0.6-seed0
#python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-alpha0.6-seed228
#python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.6 --exp-name ucfg1-CLIP_B-alpha0.6-seed3407
#echo "3.9 ucfg1-CLIP_B-alpha0.6 Run finish on 3090!"
#
#python main_mixup.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-alpha0.5-seed0
#python main_mixup.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-alpha0.5-seed228
#python main_mixup.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --mixup_alpha 0.5 --exp-name ucfg1-CLIP_B-alpha0.5-seed3407
#echo "3.9 ucfg1-CLIP_B-alpha0.5 Run finish on 3090!"

## 3.4
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_B-VLR0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_B-VLR0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg2-CLIP_B-VLR0.5-seed3407
#wait
#echo "3.4 ucfg2-CLIP_B-VLR0.5 Run finish!"
#
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg2-CLIP_B-VLR2.0-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg2-CLIP_B-VLR2.0-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg2-CLIP_B-VLR2.0-seed3407
#wait
#echo "3.3 ucfg2-CLIP_B-VLR2.0 Run finish!"
#
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.1 --exp-name ucfg1-CLIP_B-VLR0.1-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.1 --exp-name ucfg1-CLIP_B-VLR0.1-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.1 --exp-name ucfg1-CLIP_B-VLR0.1-seed3407
#wait
#echo "3.4 ucfg1-CLIP_B-VLR0.1 Run finish!"
#
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_B-VLR0.5-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_B-VLR0.5-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 0.5 --exp-name ucfg1-CLIP_B-VLR0.5-seed3407
#wait
#echo "3.4 ucfg1-CLIP_B-VLR0.5 Run finish!"
#
#CUDA_VISIBLE_DEVICES=0 python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg1-CLIP_B-VLR2.0-seed0 &
#CUDA_VISIBLE_DEVICES=1 python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg1-CLIP_B-VLR2.0-seed228 &
#CUDA_VISIBLE_DEVICES=2 python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --VLR 2.0 --exp-name ucfg1-CLIP_B-VLR2.0-seed3407
#wait
#echo "3.3 ucfg1-CLIP_B-VLR2.0 Run finish!"

# 3.3
#python main_difLR.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-VLR0.1-seed0
#python main_difLR.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-VLR0.1-seed228
#python main_difLR.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-VLR0.1-seed3407
#echo "3.3 ucfg2-CLIP_B-VLR0.1 Run finish!"

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_abn-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_abn-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-abn.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_abn-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_nor-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip-no-nor.list  --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-no_nor-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/violence-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-seed0

#python main.py --seed 0 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg2 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg2-clip.list --test_rgb_list list/GV/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg2-CLIP_B-seed3407

#python main.py --seed 0 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-seed0

#python main.py --seed 0 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list  --exp-name violence-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list --beta 0.001 --gama 0.1
#python main.py --seed 3407 --feat_extractor clip --dataset violence --feature-group both --fusion add --batch-size 32 --aggregate_text --extra_loss --feature-size 512 --rgb_list list/violence-clip.list --test_rgb_list list/violence-clip-test.list --beta 0.001 --gama 0.1

#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-seed3407
#
#python main.py --seed 0 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-3000e-seed0
#python main.py --seed 228 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-3000e-seed228
#python main.py --seed 3407 --max-epoch 3000 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-nor.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_nor-3000e-seed3407

#
#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_abn-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_abn-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip-no-abn.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-no_abn-seed3407
#
#python main.py --seed 0 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfg1 --feature-size 512 --batch-size 32 --rgb_list list/GV/ucfg1-clip.list --test_rgb_list list/GV/ucfg1-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucfg1-CLIP_B-seed3407
#
#python main.py --seed 0 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-seed0
#python main.py --seed 228 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-seed228
#python main.py --seed 3407 --feat_extractor clip --dataset ucfcrime --feature-size 512 --batch-size 32 --rgb_list list/ucf-clip-train.list --test_rgb_list list/ucf-clip-test.list --feature-group both --fusion concat --emb_folder sent_emb_n --emb_dim 768 --aggregate_text --extra_loss --use_dic_gt  --exp-name ucf-CLIP_B-seed3407

python ./tools/get_best_ap_auc.py # > /dev/null 2>&1

end_time=$(date +%s)
runtime_hours=$(((end_time - start_time)/3600))
echo "任务运行时间：$runtime_hours 小时"
date +"%Y-%m-%d %H:%M:%S"